"""Add Eent Model for countdown timers

Revision ID: 00d98acebc71
Revises: bf0e4cac2611
Create Date: 2025-03-06 16:25:13.137186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d98acebc71'
down_revision = 'bf0e4cac2611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('hashtags',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('hashtags',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
